CREATE EVENT IF NOT EXISTS `idempotency_keys_cleanup`
ON SCHEDULE EVERY 15 MINUTE
STARTS CURRENT_TIMESTAMP
ON COMPLETION PRESERVE
ENABLE
DO
  DELETE FROM `idempotency_keys`
  WHERE `expires_at` <= UTC_TIMESTAMP(3)
  LIMIT 1000;
